DEFAULT_MEDICAL_SETTINGS_AND_DOMAINS = [
    ("ICU", "general internal medicine"),
    ("Emergency Department", "general internal medicine"),
    ("General Ward", "general internal medicine"),
    ("Hospice", "general internal medicine"),
    ("ICU", "cardiology"),
    ("Emergency Department", "cardiology"),
    ("General Ward", "cardiology"),
    ("ICU", "pulmonology"),
    ("Emergency Department", "pulmonology"),
    ("ICU", "nephrology"),
    ("Emergency Department", "nephrology"),
    ("General Ward", "nephrology"),
    ("Hospice", "nephrology"),
    ("Emergency Department", "endocrinology"),
    ("General Ward", "endocrinology"),
    ("ICU", "oncology"),
    ("Outpatient Clinic", "oncology"),
    ("Emergency Department", "oncology"),
    ("General Ward", "oncology"),
    ("Hospice", "oncology"),
    ("ICU", "geriatrics"),
    ("Outpatient Clinic", "geriatrics"),
    ("Emergency Department", "geriatrics"),
    ("General Ward", "geriatrics"),
    ("Hospice", "geriatrics"),
    ("ICU", "palliative care"),
    ("Emergency Department", "palliative care"),
    ("General Ward", "palliative care"),
    ("Hospice", "palliative care"),
    ("Emergency Department", "emergency medicine"),
    ("ICU", "critical care medicine"),
    ("Outpatient Clinic", "psychiatry"),
    ("Emergency Department", "psychiatry"),
    ("General Ward", "psychiatry"),
    ("ICU", "neurology"),
    ("Emergency Department", "neurology"),
    ("General Ward", "neurology"),
    ("Hospice", "neurology"),
    ("Outpatient Clinic", "infectious diseases"),
    ("Emergency Department", "infectious diseases"),
    ("General Ward", "infectious diseases"),
    ("ICU", "general surgery"),
    ("Emergency Department", "general surgery"),
    ("General Ward", "general surgery"),
    ("ICU", "orthopedic surgery"),
    ("Emergency Department", "orthopedic surgery"),
    ("General Ward", "orthopedic surgery"),
    ("ICU", "obstetrics and gynecology"),
    ("Outpatient Clinic", "obstetrics and gynecology"),
    ("Emergency Department", "obstetrics and gynecology"),
    ("General Ward", "obstetrics and gynecology"),
    ("ICU", "pediatrics"),
    ("Emergency Department", "pediatrics"),
    ("General Ward", "pediatrics"),
    ("Outpatient Clinic", "pediatrics"),
    ("Outpatient Clinic", "family medicine"),
]   

VALUES_WITHIN_PAIRS = [
    ("autonomy", "beneficence"),
    ("autonomy", "non-maleficence"),
    ("beneficence", "non-maleficence"),
    ("beneficence", "justice"),
    ("non-maleficence", "justice"),
]